name: sys-backend-app

services:
  - name: sys-backend
    image:
      registry_type: DOCR
      registry: dev-registry-2025
      repository: sys-backend
      tag: latest
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
    run_command: "node dist/index.js"
    health_check:
      http_path: /health
    routes:
      - path: /
