name: sys-backend-app
services:
  - name: sys-backend
    image:
      registry: registry.digitalocean.com/dev-registry-2025
      repository: sys-backend
      tag: latest
      registry_type: DOCR
    http_port: 8080
