name: sys-backend-app
services:
  - name: sys-backend
    image:
      registry_type: DOCR
      repository: dev-registry-2025/sys-backend
      tag: latest
    envs:
      - key: NODE_ENV
        value: production
    health_check:
      http_path: /health
