name: sys-backend-app

services:
  - name: sys-backend
    image:
      registry_type: DOCR
      registry: dev-registry-2025
      repository: sys-backend
      tag: latest
    envs:
      - key: NODE_ENV
        value: production
    health_check:
      http_path: /health
      port: 8080 # Asegúrate de que esté usando el puerto correcto

