name: CI/CD Pipeline for DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ vars.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ vars.DIGITALOCEAN_USERNAME }}
          password: ${{ vars.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set version tag
        run: echo "IMAGE_TAG=v${{ github.sha }}" >> $GITHUB_ENV # Usamos run_id de GitHub como tag único

      - name: Build and tag Docker image
        run: docker build -t registry.digitalocean.com/dev-registry-2025/sys-backend:${{ env.IMAGE_TAG }} .

      - name: Replace image tag in app.yaml
        run: sed -i 's/TAG_PLACEHOLDER/'"$IMAGE_TAG"'/g' .apps/app-master.yaml

      - name: Push Docker image to DigitalOcean Registry
        run: docker push registry.digitalocean.com/dev-registry-2025/sys-backend:${{ env.IMAGE_TAG }}

      - name: Install DigitalOcean CLI
        run: |
          curl -fsSL https://github.com/digitalocean/doctl/releases/download/v1.123.0/doctl-1.123.0-linux-amd64.tar.gz -o doctl.tar.gz
          tar xzf doctl.tar.gz
          chmod +x doctl
          sudo mv doctl /usr/local/bin/
          doctl version  # Verifica si `doctl` se instaló correctamente

      - name: Authenticate with DigitalOcean
        run: doctl auth init --access-token ${{ vars.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DigitalOcean Container Registry
        run: doctl registry login

      - name: Verify Image in DigitalOcean Registry
        run: doctl registry repository list-tags sys-backend

      - name: Deploy to DigitalOcean App Platform
        run: doctl apps update ${{ vars.DIGITALOCEAN_WS_ID_PROD }} --spec .apps/app-master.yaml --wait --update-sources
