name: CI/CD Pipeline for DigitalOcean

on:
  push:
    branches:
      - develop # Este es el branch que disparará el flujo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Build and push Docker image to DigitalOcean Container Registry
        run: |
          docker build -t registry.digitalocean.com/dev-registry-2025/sys-backend:latest .
          docker push registry.digitalocean.com/dev-registry-2025/sys-backend:latest

      - name: Install DigitalOcean CLI
        run: |
          curl -fsSL https://github.com/digitalocean/doctl/releases/download/v1.123.0/doctl-1.123.0-linux-amd64.tar.gz -o doctl.tar.gz
          tar xzf doctl.tar.gz
          chmod +x doctl
          sudo mv doctl /usr/local/bin/
          doctl version  # Verifica si `doctl` se instaló correctamente

      - name: Deploy to DigitalOcean App Platform
        run: |
          doctl auth init --access-token ${{ secrets.DO_ACCESS_TOKEN }}
          doctl apps update sys-backend-app --spec app.yaml --wait
